src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * User
 *
 * @ORM\Table(name="fos_user")
 * @ORM\Entity
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 *
 */
class User extends BaseUser
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Please enter your name.", groups={"Registration", "Profile"})
     * @Assert\Length(
     *     min=3,
     *     max=255,
     *     minMessage="The name is too short.",
     *     maxMessage="The name is too long.",
     *     groups={"Registration", "Profile"}
     * )
     */
    protected $name;

    /**
     * @var boolean
     *
     * @ORM\Column(name="status", type="boolean")
     */
    protected $status = true;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Please enter your surname.", groups={"Registration", "Profile"})
     * @Assert\Length(
     *     min=3,
     *     max=255,
     *     minMessage="The surname is too short.",
     *     maxMessage="The surname is too long.",
     *     groups={"Registration", "Profile"}
     * )
     */
    protected $surname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Please enter your patronymic.", groups={"Registration", "Profile"})
     * @Assert\Length(
     *     min=3,
     *     max=255,
     *     minMessage="The patronymic is too short.",
     *     maxMessage="The patronymic is too long.",
     *     groups={"Registration", "Profile"}
     * )
     */
    protected $patronymic;

    /**
     * @var bool
     * @ORM\Column(name="is_notified", type="boolean", nullable=true)
     */
    protected $isNotified;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $phone_number;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="avatar_file", fileNameProperty="avatar")
     *
     * @var File
     */
    protected $imageFile;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="text", nullable=true, unique=false)
     */
    protected $avatar;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="register_date", type="datetime", nullable=true)
     */
    protected $registerDate;

    /**
     * @var int
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\BattleResult", mappedBy="user")
     */
    protected $battleResults;
    /**
     * @var int
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\BattleResult", mappedBy="opponent")
     */
    protected $opponentForUser;

    /**
     * @var League
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\League", inversedBy="users")
     */
    protected $league;
    /**
     * @var int
     * @ORM\Column(name="balance", type="integer", nullable=true)
     */
    protected $balance;

    /**
     * @var int
     * * @ORM\Column(name="points", type="integer", nullable=true)
     */
    protected $points;

    /**
     * @var
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Badge", mappedBy="user")
     */
    protected $badges;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\History", mappedBy="user")
     */
    protected $histories;

    /**
     * @ORM\PrePersist()
     *
     */
    public function prePersist()
    {
        $this->registerDate = new \DateTime;
    }

    public function __construct() {
        parent::__construct();
        $this->battleResults = new ArrayCollection();
        $this->opponentForUser = new ArrayCollection();
        $this->histories = new ArrayCollection();
        $this->quartets = new ArrayCollection();
        $this->badges = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->email ?: '';
    }

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Office", inversedBy="users")
     */
    protected $office;

    public function setOffice(Office $office)
    {
        $this->office = $office;
        return $this;
    }

    public function getOffice()
    {
        return $this->office;
    }

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Quartet", inversedBy="users")
     */
    protected $quartets;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return mixed
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * @param mixed $phone_number
     * @return $this
     */
    public function setPhoneNumber($phone_number)
    {
        $this->phone_number = $phone_number;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * @param mixed $surname
     * @return $this
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPatronymic()
    {
        return $this->patronymic;
    }

    /**
     * @param mixed $patronymic
     * @return $this
     */
    public function setPatronymic($patronymic)
    {
        $this->patronymic = $patronymic;
        return $this;
    }

    /**
     * @return bool
     */
    public function isNotified()
    {
        return $this->isNotified;
    }

    /**
     * @param bool $isNotified
     */
    public function setIsNotified(bool $isNotified)
    {
        $this->isNotified = $isNotified;
    }

    /**
     * get avatar
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param string $avatar
     */
    public function setAvatar(string $avatar = null)
    {
        $this->avatar = $avatar;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     *
     * @param File|null $imageFile
     * @return User
     */
    public function setImageFile(File $imageFile = null)
    {
        $this->imageFile = $imageFile;
        return $this;
    }

    /**
     * Get isNotified
     *
     * @return boolean
     */
    public function getIsNotified()
    {
        return $this->isNotified;
    }

    /**
     * Set registerDate
     *
     * @param \DateTime $registerDate
     *
     * @return User
     */
    public function setRegisterDate($registerDate)
    {
        $this->registerDate = $registerDate;

        return $this;
    }

    /**
     * Get registerDate
     *
     * @return \DateTime
     */
    public function getRegisterDate()
    {
        return $this->registerDate;
    }

    /**
     * Set status
     *
     * @param boolean $status
     *
     * @return User
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return boolean
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Add battleResult
     *
     * @param \AppBundle\Entity\BattleResult $battleResult
     *
     * @return User
     */
    public function addBattleResult(\AppBundle\Entity\BattleResult $battleResult)
    {
        $this->battleResults[] = $battleResult;

        return $this;
    }

    /**
     * Remove battleResult
     *
     * @param \AppBundle\Entity\BattleResult $battleResult
     */
    public function removeBattleResult(\AppBundle\Entity\BattleResult $battleResult)
    {
        $this->battleResults->removeElement($battleResult);
    }

    /**
     * Get battleResults
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBattleResults()
    {
        return $this->battleResults;
    }

    /**
     * Add opponentForUser
     *
     * @param \AppBundle\Entity\BattleResult $opponentForUser
     *
     * @return User
     */
    public function addOpponentForUser(\AppBundle\Entity\BattleResult $opponentForUser)
    {
        $this->opponentForUser[] = $opponentForUser;

        return $this;
    }

    /**
     * Remove opponentForUser
     *
     * @param \AppBundle\Entity\BattleResult $opponentForUser
     */
    public function removeOpponentForUser(\AppBundle\Entity\BattleResult $opponentForUser)
    {
        $this->opponentForUser->removeElement($opponentForUser);
    }

    /**
     * Get opponentForUser
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOpponentForUser()
    {
        return $this->opponentForUser;
    }

    /**
     * @return int
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * @param int $balance
     */
    public function setBalance(int $balance)
    {
        $this->balance = $balance;
    }

    /**
     * Set league
     *
     * @param \AppBundle\Entity\League $league
     *
     * @return User
     */
    public function setLeague(\AppBundle\Entity\League $league = null)
    {
        $this->league = $league;

        return $this;
    }

    /**
     * Get league
     *

src/AppBundle/Resources/views/basic/all_users.html.twig
{% extends 'AppBundle::main.html.twig' %}

{% block content %}
    <div class="container" id="content">
            <h1 style="text-align: center">Список Игроков</h1>
            <h3 style="text-align: center">Количество зарегистрированных пользователей {{ users }}</h3>
            <!-- Table -->
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Логин</th>
                </tr>
                </thead>

                <tbody>
                {% set count = 0 %}
                {% for user in paginate %}
                    {% set count = count + 1 %}

                    <tr data-href="{{ path('profile', {'user_id': user.id}) }}" id="{{ user.id }}">
                        <td>
                            {{ count }}
                        </td>
                        <td>
                            {{ user.name }}
                        </td>
                        <td>
                            {{ user.surname }}
                        </td>
                        <td>
                            {{ user.username }}
                        </td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>

            <div class="navigation">
                {{ knp_pagination_render(paginate) }}
            </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('table tr').click(function () {
                window.location = $(this).data('href');
                return false;
            });
        });
    </script>

{% endblock %}

src/AppBundle/Resources/views/basic/edit_profile.html.twig
{% extends 'AppBundle::main.html.twig' %}

{% block content %}
    <div class="jumbotron">
        <div class="container content">
            <div class="row">
                <div class="col-lg-3">
                    {{ form_start(form) }}
                    <img class="img-responsive" src="{{ vich_uploader_asset(profile, 'imageFile') }}">
                    <br>
                </div>
                <div class="col-lg-6">
                    <table border="0" cellpadding="3" class="table">
                        <tr>
                            <th>
                                <h5>Фамилия</h5>
                            </th>
                            <td>
                                <h5> {{ profile.surname }} </h5>
                                {{ form_row(form.surname, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <h5>Имя</h5>
                            </th>
                            <td>
                                <h5>{{ profile.name }} </h5>
                                {{ form_row(form.name, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <h5>Отчество</h5>
                            </th>
                            <td>
                                <h5> {{ profile.patronymic }}</h5>
                                 {{ form_row(form.patronymic, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <h5>email</h5>
                            </th>
                            <td>
                                <h5>{{ profile.email }}</h5>
                                {{ form_row(form.email, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <h5>Номер</h5>
                            </th>
                            <td>
                                <h5>{{ profile.phoneNumber }}</h5>
                                {{ form_row(form.phone_number, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <h5>Офис</h5>
                            </th>
                            <td>
                                <h5>{{ profile.office.name }}</h5>
                                {{ form_row(form.office, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                            </th>
                            <td>
                                {{ form_row(form, {'label':' ' }) }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                {{ form_end(form) }}
                            </td>
                        </tr>
                    </table>

                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block message %}

{% endblock %}

src/AppBundle/Resources/views/basic/game.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}
{% block sonata_admin_content %}
    <div class="col-lg-6">
        <form action="{{ path('start_game') }}">
            Date:
            <input type="date" class="form-control" name="date">
            <input type="submit" id="Начать игру">
        </form>
    </div>
{% endblock %}

src/AppBundle/Resources/views/basic/index.html.twig
{% extends "@App/main.html.twig" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="content">
                {% for an in announcement %}
                    <h2>{{ an.announcement }}</h2>
                {% endfor %}
                <p>This is main page for beeline-gamification project</p>
            </div>
            {% if message != null %}
                {{ message }}
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block message %}
{% endblock %}

src/AppBundle/Resources/views/basic/profile.html.twig
{% extends 'AppBundle::main.html.twig' %}

{% block content %}
    <div class="jumbotron">
        <div class="container content">
            <div class="row">
                < class="col-lg-3">
                {% if user_for_profile.username == profile.username %}
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                {% endif %}
                <img class="img-responsive" src="{{ vich_uploader_asset(profile, 'imageFile') }}">
                <div class="dropdown">
                    <h3 onclick="myFunction()" data-toggle="dropdown" class="dropdown-toggle"> История <b
                                class="caret"></b></h3>
                    <div id="myDropdown" class="history_menu" align="center">
                        {% for history in profile.histories %}
                            <h4><b>{{ history.office.name }}</b></h4>
                            <p class="p_history"> start_date {{ history.startDate|date('Y-M-d') }} </p>
                            {% if history.endDate is not null %}
                                <p class="p_history"> end_date {{ history.endDate|date('Y-M-d') }} </p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% for badge in  profile.badges %}
                    <h3 style="text-align: left">{{ badge.name }}</h3>
                    <img height="100" width="100" class="img-responsive"
                         src="{{ vich_uploader_asset(badge, 'badgeFile') }}">
                {% endfor %}
                    
            </div>
            <div class="col-lg-6">
                <table border="0" cellpadding="3" class="table">
                    {% if user_for_profile.username == profile.username %}
                        <tr>
                            <th>
                                <h5> Редактировать профиль</h5>
                            </th>
                            <td>
                                <form action="{{ path('edit_profile', {'user_id': profile.id}) }}">
                                    <button class="btn btn-action">редактировать</button>
                                </form>

                            </td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th>
                            <h5>ФИО</h5>
                        </th>
                        <td>
                            <h5>{{ profile.name }} {{ profile.surname }} {{ profile.patronymic }}</h5>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <h5>Логин</h5>
                        </th>
                        <td>
                            <h5>{{ profile.username }}</h5>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <h5>ОПиО</h5>
                            <h5>Регион</h5>
                        </th>
                        <td>
                            <h5>{{ profile.office }}</h5>
                            <h5>{{ profile.office.region }}</h5>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <h5>Партнер</h5>
                        </th>
                        <td>
                            <h5>{{ profile.office.partner }}</h5>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <h5>Номер</h5>
                            <h5>email</h5>
                        </th>
                        <td>
                            <h5>{{ profile.phoneNumber }}</h5>
                            <h5>{{ profile.email }}</h5>
                        </td>
                    </tr>
                    {% if not is_granted('ROLE_USER') %}
                        <tr>
                            <th>
                                <h5>Дата регистрации</h5>
                            </th>
                            <td>
                                <h5>{{ profile.registerDate|date('Y-M-d') }}</h5>
                            </td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th>
                            <h5>Статус</h5>
                        </th>
                        <td>
                            {% if profile.status == 1 %}
                                <h5>Активен</h5>
                            {% else %}
                                <h5>Не активен</h5>
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <h5>Баланс</h5>
                        </th>
                        <td>
                            {{ profile.balance }}
                        </td>
                    </tr>
                    <tr>
                        <th>

                        </th>
                        <td>

                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>

    <script>
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
    </script>
{% endblock %}